# Generated by Django 4.1.3 on 2022-11-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_pharmacuticalfarm',
            field=models.BooleanField(default=False, verbose_name='Is pharmacutical farm'),
        ),
    ]
