# Generated by Django 4.1.3 on 2022-11-16 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0002_alter_user_is_pharmacuticalfarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proPic', models.ImageField(blank=True, upload_to='ProfilePic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PharInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegiNo', models.CharField(max_length=30, unique=True)),
                ('reg_type', models.CharField(choices=[('B.Pharm(A)', 'B.Pharm(A)'), ('Diploma in pharmacy(B)', 'Diploma in pharmacy(B)'), ('Pharmacy Technician(C)', 'Pharmacy Technician(C)')], max_length=25)),
                ('division', models.CharField(max_length=24)),
                ('district', models.CharField(max_length=24)),
                ('upazilla', models.CharField(max_length=24)),
                ('last_updated_regi', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('services', models.CharField(blank=True, max_length=264, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=264, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmeci_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('Gender', models.CharField(choices=[('Maile', 'Maile'), ('Femail', 'Femail')], max_length=24)),
                ('weight', models.CharField(blank=True, max_length=24, null=True)),
                ('height', models.CharField(blank=True, max_length=24, null=True)),
                ('contuct_no', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegiNo', models.CharField(max_length=30, unique=True)),
                ('org_type', models.CharField(max_length=264)),
                ('division', models.CharField(max_length=24)),
                ('district', models.CharField(max_length=24)),
                ('upazilla', models.CharField(max_length=24)),
                ('last_updated_regi', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('services', models.CharField(blank=True, max_length=264, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=264, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BmdcRegiNo', models.IntegerField(unique=True)),
                ('reg_type', models.CharField(choices=[('Medical', 'Medical'), ('Dental', 'Dental'), ('Medical assistant', 'Medical assistant'), ('Foreign Doctor', 'Foreign Doctor')], max_length=25)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(choices=[('Maile', 'Maile'), ('Femail', 'Femail')], max_length=24)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('services', models.CharField(blank=True, max_length=264, null=True)),
                ('specialization', models.CharField(blank=True, max_length=264, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
