# Generated by Django 4.1.3 on 2022-11-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0003_userpropic_pharinfo_patientinfo_orginfo_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpropic',
            name='proPic',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_pic'),
        ),
    ]
