# Generated by Django 4.1.3 on 2022-11-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0004_alter_userpropic_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='BmdcRegiNo',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Maile', 'Maile'), ('Femail', 'Femail')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='reg_type',
            field=models.CharField(blank=True, choices=[('Medical', 'Medical'), ('Dental', 'Dental'), ('Medical assistant', 'Medical assistant'), ('Foreign Doctor', 'Foreign Doctor')], max_length=25, null=True),
        ),
    ]
