# Generated by Django 4.1.3 on 2022-11-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0005_alter_doctorinfo_bmdcregino_alter_doctorinfo_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='Degree',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='work_location',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
