# Generated by Django 4.1.3 on 2022-11-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0006_doctorinfo_degree_doctorinfo_work_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginfo',
            name='fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='instra',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='tw',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharinfo',
            name='fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharinfo',
            name='instra',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharinfo',
            name='tw',
            field=models.URLField(blank=True, null=True),
        ),
    ]
