# Generated by Django 4.1.3 on 2022-11-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0007_orginfo_fb_orginfo_instra_orginfo_tw_pharinfo_fb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharinfo',
            old_name='reg_type',
            new_name='org_type',
        ),
    ]
