# Generated by Django 4.1.3 on 2022-11-22 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0008_rename_reg_type_pharinfo_org_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovEmpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('emp_type', models.CharField(blank=True, choices=[('Medical', 'Medical'), ('Dental', 'Dental'), ('Medical assistant', 'Medical assistant'), ('Foreign Doctor', 'Foreign Doctor')], max_length=25, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Maile', 'Maile'), ('Femail', 'Femail')], max_length=24, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='govt_emp_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
