# Generated by Django 4.1.3 on 2022-11-25 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0010_alter_orginfo_regino_alter_orginfo_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expecting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expecting_ac', to=settings.AUTH_USER_MODEL)),
                ('toverify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_verify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
