# Generated by Django 4.1.3 on 2022-11-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0011_verify_delete_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verify',
        ),
    ]
