# Generated by Django 4.1.3 on 2022-11-21 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('review_date', models.DateField(auto_now_add=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_giver', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='Reting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_stars', models.IntegerField()),
                ('retgiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_giver', to=settings.AUTH_USER_MODEL)),
                ('retrecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reting_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField(blank=True, null=True, verbose_name='Advice medical test...')),
                ('disease', models.TextField(blank=True, null=True, verbose_name='Patient disease...')),
                ('prescrb', models.TextField(blank=True, null=True, verbose_name='Prescribe medicine...')),
                ('Advice', models.TextField(blank=True, null=True, verbose_name='Consult...')),
                ('prescrb_img', models.ImageField(blank=True, null=True, upload_to='prescribeImg', verbose_name='Image')),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribe_giver', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribe_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creat_date',),
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('permission_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_giver', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=264, null=True, verbose_name='Report title ')),
                ('doctor', models.CharField(blank=True, max_length=24, null=True, verbose_name='Dr. username')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Medical report......')),
                ('Advice', models.TextField(blank=True, null=True, verbose_name='Advice')),
                ('report_img', models.ImageField(blank=True, null=True, upload_to='TestReportImg', verbose_name='Report Image')),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_report_giver', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_report_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creat_date',),
            },
        ),
        migrations.CreateModel(
            name='MedicaleRocord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=264, null=True, verbose_name='Record title ')),
                ('record', models.TextField(blank=True, null=True, verbose_name='Medical record......')),
                ('Advice', models.TextField(blank=True, null=True, verbose_name='Advice')),
                ('record_img', models.ImageField(blank=True, null=True, upload_to='medical_record', verbose_name='Record Image')),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_record_giver', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_record_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creat_date',),
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_Review', to='prescribeapp.review')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
