# Generated by Django 4.1.3 on 2022-11-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescribeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltestreport',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_test', to='prescribeapp.prescription'),
        ),
    ]
