# Generated by Django 4.1.3 on 2022-11-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescribeapp', '0002_medicaltestreport_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalerocord',
            name='purpose',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Purpose'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='purpose',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Purpose'),
        ),
    ]
